# Generated by Django 6.0.2 on 2026-02-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_short_code_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitsmeasurement',
            options={'ordering': ['name']},
        ),
    ]
