# Generated by Django 6.0.2 on 2026-02-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
